version: '2'

services:
  proxy:
    build: .
    env_file:
     - ./api.env
    environment:
    - FORCE_HTTPS=false
    volumes:
    - ./lua:/lua
    ports:
      - 80:80
      - 8080:8080
      - 443:443
