version: '2'

services:
  proxy:
    image: proxylua
    volumes:
    - ./configs:/etc/nginx/conf.d
    env_file:
     - ./api.env
    environment:
    - FORCE_HTTPS=false
    ports:
      - 80:80
      - 8080:8080
      - 443:443
