version: '2'

services:
  proxy:
    build: ./
    volumes:
    - ./configs:/etc/nginx/conf.d
    - ./lua:/lua
    environment:
    - FORCE_HTTPS=false
    - USERNAME=admin
    - PASSWORD=test1
    ports:
      - 80:80
      - 8080:8080
      - 443:443
